print('+---------------------------------------------------------------------+')
print('|                                                           June 2025 |')
print('|                                                     Kerala, IN      |')
print('|  Dear Me,                                                           |')
print('|                                                                     |')
print('|      Dream big, but act small—every line of code counts.            |')
print('|      Stay curious, stay kind.                                       |')
print('|      Build for impact, not applause.                                |')
print('|      Failure is feedback, not defeat.                               |')
print('|      Be the big guy you once wished you were                        |')
print('|                                                                     |')
print('|                                    - The future ai/ml researcher 💻 |')
print('|                                                                     |')
print('+---------------------------------------------------------------------+')
